import type { FormTemplate } from './types';

export const FORM_TEMPLATES: FormTemplate[] = [
  {
    id: 'form-contact-information',
    app: 'FORM',
    name: 'Contact Information',
    subtitle: 'Collect details',
    category: 'Personal',
    description: 'Please share your contact details so we can stay in touch.',
    theme: { primaryColor: '#1a73e8', backgroundColor: '#e8f0fe', fontFamily: 'sans' },
    fields: [
      { type: 'SHORT_ANSWER', label: 'Name', required: true },
      { type: 'EMAIL', label: 'Email', required: true },
      { type: 'SHORT_ANSWER', label: 'Phone number', validation: { pattern: '^[0-9+()\\-. ]{7,20}$', patternMessage: 'Enter a valid phone number' } },
      { type: 'PARAGRAPH', label: 'Address' },
      { type: 'PARAGRAPH', label: 'Comments' },
    ],
  },
  {
    id: 'form-rsvp',
    app: 'FORM',
    name: 'RSVP',
    subtitle: 'Event reply',
    category: 'Personal',
    description: 'Event Address: 123 Your Street, Your City, ST 12345\nContact us at (123) 456-7890 or no_reply@example.com',
    theme: { primaryColor: '#d93025', backgroundColor: '#fce8e6', fontFamily: 'serif' },
    fields: [
      { type: 'MULTIPLE_CHOICE', label: 'Can you attend?', required: true, options: ['Yes, I’ll be there', 'Sorry, can’t make it'] },
      { type: 'SHORT_ANSWER', label: 'What are the names of people attending?' },
      { type: 'NUMBER', label: 'How many guests are you bringing?', validation: { min: 0, max: 10, integer: true } },
      { type: 'CHECKBOXES', label: 'Dietary restrictions', options: ['Vegetarian', 'Vegan', 'Gluten-free', 'Nut allergy', 'None'] },
      { type: 'PARAGRAPH', label: 'Comments and/or questions' },
    ],
  },
  {
    id: 'form-event-registration',
    app: 'FORM',
    name: 'Event Registration',
    subtitle: 'Sign-ups',
    category: 'Work',
    description: 'Event Timing: January 4th–6th, 2027\nEvent Address: 123 Your Street, Your City, ST 12345\nContact us at (123) 456-7890 or no_reply@example.com',
    theme: { primaryColor: '#0b8043', backgroundColor: '#e6f4ea', fontFamily: 'sans' },
    fields: [
      { type: 'SHORT_ANSWER', label: 'Name', required: true },
      { type: 'EMAIL', label: 'Email', required: true },
      { type: 'SHORT_ANSWER', label: 'Organization' },
      { type: 'CHECKBOXES', label: 'What days will you attend?', required: true, options: ['Day 1', 'Day 2', 'Day 3'] },
      { type: 'MULTIPLE_CHOICE', label: 'Dietary restrictions', options: ['None', 'Vegetarian', 'Vegan', 'Kosher', 'Gluten-free'] },
      { type: 'DROPDOWN', label: 'How did you hear about this event?', options: ['Email', 'Social media', 'A colleague', 'Website', 'Other'] },
    ],
  },
  {
    id: 'form-customer-feedback',
    app: 'FORM',
    name: 'Customer Feedback',
    subtitle: 'Ratings and comments',
    category: 'Work',
    description: 'We would love to hear your thoughts or feedback on how we can improve your experience!',
    theme: { primaryColor: '#e8710a', backgroundColor: '#feefe3', fontFamily: 'sans' },
    fields: [
      { type: 'MULTIPLE_CHOICE', label: 'Feedback type', options: ['Comments', 'Questions', 'Bug reports', 'Feature request'] },
      { type: 'RATING', label: 'Overall, how satisfied are you with us?', required: true, settings: { scaleMax: 5 } },
      {
        type: 'LINEAR_SCALE',
        label: 'How likely are you to recommend us to a friend?',
        settings: { scaleMin: 0, scaleMax: 10, minLabel: 'Not at all likely', maxLabel: 'Extremely likely' },
      },
      { type: 'PARAGRAPH', label: 'Feedback', required: true },
      { type: 'EMAIL', label: 'Email (if you would like a reply)' },
    ],
  },
  {
    id: 'form-job-application',
    app: 'FORM',
    name: 'Job Application',
    subtitle: 'Hiring',
    category: 'Work',
    description: 'Thank you for your interest in working with us. Please fill out the form below to apply.',
    theme: { primaryColor: '#3949ab', backgroundColor: '#e8eaf6', fontFamily: 'sans' },
    fields: [
      { type: 'SHORT_ANSWER', label: 'Name', required: true },
      { type: 'EMAIL', label: 'Email', required: true },
      { type: 'SHORT_ANSWER', label: 'Phone number', required: true },
      { type: 'DROPDOWN', label: 'Which position are you applying for?', required: true, options: ['Position one', 'Position two', 'Position three'] },
      { type: 'DATE', label: 'When can you start?' },
      { type: 'FILE_UPLOAD', label: 'Resume', required: true, settings: { maxFiles: 1, maxFileSizeMb: 10, allowedFileTypes: ['pdf', 'document'] } },
      { type: 'PARAGRAPH', label: 'Why would you like to join us?' },
    ],
  },
  {
    id: 'form-course-evaluation',
    app: 'FORM',
    name: 'Course Evaluation',
    subtitle: 'End of term',
    category: 'Education',
    description: 'Your answers are used to improve this course. Thank you for your honest feedback.',
    theme: { primaryColor: '#00796b', backgroundColor: '#e0f2f1', fontFamily: 'serif' },
    fields: [
      { type: 'SHORT_ANSWER', label: 'Course name', required: true },
      { type: 'LINEAR_SCALE', label: 'The course objectives were clear.', required: true, settings: { scaleMin: 1, scaleMax: 5, minLabel: 'Strongly disagree', maxLabel: 'Strongly agree' } },
      { type: 'LINEAR_SCALE', label: 'The workload was appropriate.', required: true, settings: { scaleMin: 1, scaleMax: 5, minLabel: 'Strongly disagree', maxLabel: 'Strongly agree' } },
      { type: 'SECTION', label: 'About the instructor', description: 'Tell us about the teaching in this course.' },
      { type: 'RATING', label: 'How would you rate the instructor overall?', required: true, settings: { scaleMax: 5 } },
      { type: 'PARAGRAPH', label: 'What did the instructor do well?' },
      { type: 'PARAGRAPH', label: 'What could be improved?' },
    ],
  },
  {
    id: 'form-nps-survey',
    app: 'FORM',
    name: 'NPS Survey',
    subtitle: 'One question at a time',
    category: 'Work',
    description: 'Three quick questions about your experience.',
    conversational: true,
    theme: { primaryColor: '#4f46e5', backgroundColor: '#eef2ff', fontFamily: 'sans' },
    settings: { layout: 'conversational', showProgressBar: true, showTimeEstimate: true },
    fields: [
      { type: 'WELCOME', label: 'We value your honest feedback', description: 'It takes under a minute.', settings: { buttonLabel: 'Start survey' } },
      { type: 'NPS', label: 'How likely are you to recommend us to a friend or colleague?', required: true },
      { type: 'RATING', label: 'How satisfied are you with our service?', required: true, settings: { scaleMax: 5 } },
      { type: 'MULTIPLE_CHOICE', label: 'What do you value most?', options: ['Quality', 'Price', 'Support', 'Speed'] },
      { type: 'PARAGRAPH', label: 'What could we do better?', validation: { maxLength: 1000 }, settings: { showCharCount: true } },
      { type: 'ENDING', label: 'Thank you!', description: 'Your feedback helps us improve.', settings: { badgeIcon: 'heart' } },
    ],
  },
  {
    id: 'form-lead-capture',
    app: 'FORM',
    name: 'Lead Capture',
    subtitle: 'One question at a time',
    category: 'Work',
    description: "Tell us a little about you and we'll be in touch.",
    conversational: true,
    theme: { primaryColor: '#0f766e', backgroundColor: '#f0fdfa', fontFamily: 'sans' },
    settings: { layout: 'conversational', showProgressBar: true },
    fields: [
      { type: 'WELCOME', label: "Let's talk", description: 'Answer a few questions and our team will reach out.', settings: { buttonLabel: 'Get started' } },
      { type: 'SHORT_ANSWER', label: "What's your name?", required: true, validation: { requiredMessage: 'We need a name to address you by.' } },
      { type: 'EMAIL', label: "What's your work email?", required: true, validation: { requiredMessage: 'We need your email to reply.' } },
      { type: 'PHONE', label: 'Phone number (optional)' },
      { type: 'DROPDOWN', label: 'How big is your company?', required: true, options: ['1–10 people', '11–50 people', '51–250 people', '250+ people'] },
      { type: 'NUMBER', label: "What's your monthly budget?", validation: { min: 0 }, settings: { prefix: '$' } },
      { type: 'ENDING', label: "Thanks — we'll be in touch soon", settings: { badgeIcon: 'rocket', showSubmitAnother: false } },
    ],
  },
  {
    id: 'form-bug-report',
    app: 'FORM',
    name: 'Bug Report',
    subtitle: 'One question at a time',
    category: 'Work',
    description: 'Help us find and fix the problem.',
    conversational: true,
    theme: { primaryColor: '#dc2626', backgroundColor: '#fef2f2', fontFamily: 'sans' },
    settings: { layout: 'conversational', showProgressBar: true },
    fields: [
      { type: 'WELCOME', label: 'Found a bug?', description: 'Tell us what happened — the more detail, the faster we can fix it.', settings: { buttonLabel: 'Report it' } },
      { type: 'SHORT_ANSWER', label: 'Summarise the problem in one line', required: true, validation: { maxLength: 120 }, settings: { showCharCount: true } },
      { type: 'PARAGRAPH', label: 'What steps lead to the problem?', required: true },
      { type: 'MULTIPLE_CHOICE', label: 'How serious is it?', required: true, options: ['Blocks my work', 'Major', 'Minor', 'Cosmetic'] },
      { type: 'URL', label: 'Which page were you on?' },
      { type: 'FILE_UPLOAD', label: 'Add a screenshot (optional)', settings: { maxFiles: 3, maxFileSizeMb: 10, allowedFileTypes: ['image'] } },
      { type: 'EMAIL', label: 'Where can we follow up?' },
      { type: 'ENDING', label: 'Thanks for the report', description: "We'll look into it.", settings: { badgeIcon: 'thumbs_up' } },
    ],
  },
  {
    id: 'form-party-rsvp',
    app: 'FORM',
    name: 'Party RSVP',
    subtitle: 'One question at a time',
    category: 'Personal',
    description: 'Let us know if you can make it.',
    conversational: true,
    theme: { primaryColor: '#db2777', backgroundColor: '#fdf2f8', fontFamily: 'serif' },
    settings: { layout: 'conversational', showProgressBar: true },
    fields: [
      { type: 'WELCOME', label: "You're invited!", description: 'Please reply by the end of the month.', settings: { buttonLabel: 'RSVP' } },
      { type: 'SHORT_ANSWER', label: "What's your name?", required: true },
      { type: 'YES_NO', label: 'Will you be joining us?', required: true, settings: { yesLabel: 'Count me in', noLabel: "Can't make it" } },
      { type: 'NUMBER', label: 'How many guests are you bringing?', validation: { min: 0, max: 5, integer: true, rangeMessage: 'You can bring up to 5 guests.' } },
      { type: 'CHECKBOXES', label: 'Any dietary needs?', options: ['Vegetarian', 'Vegan', 'Gluten-free', 'Nut allergy', 'None'] },
      { type: 'PARAGRAPH', label: 'Anything else we should know?' },
      { type: 'ENDING', label: 'Thanks for letting us know!', settings: { badgeIcon: 'sparkles' } },
    ],
  },
  {
    id: 'form-product-feedback',
    app: 'FORM',
    name: 'Product Feedback',
    subtitle: 'One question at a time',
    category: 'Work',
    description: 'Tell us how the product works for you.',
    conversational: true,
    theme: { primaryColor: '#7c3aed', backgroundColor: '#f5f3ff', fontFamily: 'sans' },
    settings: { layout: 'conversational', showProgressBar: true, showTimeEstimate: true },
    fields: [
      { type: 'WELCOME', label: 'Help us build a better product', description: 'Five short questions.', settings: { buttonLabel: "Let's go" } },
      { type: 'EMOJI_RATING', label: 'How do you feel about the product overall?', required: true, settings: { scaleMax: 5 } },
      { type: 'SLIDER', label: 'How many hours a week do you use it?', settings: { rangeMin: 0, rangeMax: 40, step: 1, suffix: ' h' } },
      { type: 'OPINION_SCALE', label: 'How easy is it to use?', required: true, settings: { scaleMin: 1, scaleMax: 5, minLabel: 'Hard', maxLabel: 'Easy' } },
      { type: 'CHECKBOXES', label: 'Which features do you use most?', options: ['Dashboards', 'Reports', 'Integrations', 'Mobile app'] },
      { type: 'PARAGRAPH', label: "What's one thing you'd change?", validation: { maxLength: 500 }, settings: { showCharCount: true } },
      { type: 'ENDING', label: 'Thanks for helping us improve', settings: { badgeIcon: 'check' } },
    ],
  },
];
